imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        applog:
            type: stream
            path: "%kernel.logs_dir%/symfony.log"
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
            excluded_404s:
                - ^/.*
        file:
            type: stream
            level: debug
        syslog:
            type: syslog
            level: error