imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @MaximCMSBundle/Resources/config/admin.yml }
    - { resource: @MaximCMSBundle/Resources/config/role_hierarchies.yml }
parameters:
    website: 3
services:
    twig.extension.text:
         class: Twig_Extensions_Extension_Text
         tags:
             - { name: twig.extension }
    pdo:
      class: PDO
      arguments:
        - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
        - "%database_user%"
        - "%database_password%"
      calls:
         - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION
    session.handler.pdo:
       class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
       arguments: ["@pdo", "%pdo.db_options%"]
framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    esi: {enabled: true}
    translator: ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:     session.handler.pdo
#       cookie_domain:  %session.cookie_domain%
    fragments:       ~
    http_method_override: true
    templating:
        engines: 'twig'
        assets_version: 0.31
        assets_version_format: "%%s?v=%%s"
        #assets_base_urls:
        #   - http://cdn.localhost.com
        #   - http://cdn1.localhost.com
        #   - http://cdn2.localhost.com

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: "maxim_cms.controller.exception_controller:showAction"
    globals:
        maintenance: false
        social_facebook: http://www.google.com
        # enables the top bar
        # networks: <false|true>
        networks: true

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    write_to: "%kernel.root_dir%/../web/"
    bundles:        [ 'MaximCMSBundle' ]
    #java: /usr/bin/java
    filters:
        cssrewrite:
            apply_to: "\.css$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #    apply_to: "\.css$"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            apply_to: "\.css$"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            apply_to: "\.js$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   default
        entity_managers:
            default:
                #auto_mapping: true
                connection: default
                metadata_cache_driver: apc
                query_cache_driver: apc
                result_cache_driver: apc
                dql:
                    datetime_functions:
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        DATE: Maxim\CMSBundle\DQL\DateFunction
                mappings:
                    MaximCMSBundle: ~
                    MaximModuleTicketBundle: ~
                    MaximModuleForumBundle: ~
                    MaximModuleApplicationBundle: ~
                    payum:
                        is_bundle: false
                        type: xml
                        dir: %kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping
                        prefix: Payum\Core\Model
                        
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


#FOS
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Maxim\CMSBundle\Entity\User
    group:
        group_class: Maxim\CMSBundle\Entity\Rank
    from_email:
        address:     no-reply@eyeofender.com
        sender_name: Eye of Ender customer service
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled: true
            template: MaximCMSBundle:Registration:email.html.twig
        form:
            type: maxim_cms_user_registration
    profile:
        form:
            type: maxim_cms_user_profile

# Payum Configuration
payum:
    contexts:
        paypal_express_checkout_plus_doctrine:
            paypal_express_checkout_nvp:
                #options:
                #    username:  %paypal.express_checkout.username%
                #    password:  %paypal.express_checkout.password%
                #    signature: %paypal.express_checkout.signature%
                #    sandbox: %paypal.express_checkout.sandbox%
                #options:
                #    username:  'c4d3r-facilitator_api1.hotmail.com'
                #    password:  '1370531911'
                #   signature: 'A5dlNjuK3lFO0sbl9JbP7PGWYlfNAG0QiZDCPrw5l4Cl1iAJ4juv4IkT'
                #    sandbox: true
                username: 'purchases_api1.eyeofender.com'
                password: 'XFN7RBRFZ8Y9R5L4'
                signature: 'AwxVz5m1pD5T3wcCseXSpNVzLX8RAKrJrfO4ijXLiT9aVe0MMRpjeg8j'
                sandbox: false
                actions:
                    - maxim_cms.action.store_notification
    storages:
        Maxim\CMSBundle\Entity\PaymentDetails:
            doctrine: orm
    security:
        token_storage:
            Maxim\CMSBundle\Entity\PayumSecurityToken:
                doctrine:
                    driver: orm

# KNP
knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: false                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: MaximCMSBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

# SONATA
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        maxim_cms.block.latest_users: ~
        maxim_cms.block.latest_purchases: ~
        maxim_cms.block.purchases: ~
        maxim_cms.block.recache: ~
        # Your other blocks
sonata_admin:
    title:      MCSuite
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png
    security:
        handler: sonata.admin.security.handler.role
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list}
             #- { position: center, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> You can customize this dashboard by editing the sonata_admin.yml file. The current dashboard presents the recent items from the NewsBundle and a timeline with the latest action"} }
            - { position: center, type: maxim_cms.block.recache }
            - { position: center, type: maxim_cms.block.latest_users }
            - { position: right, type: maxim_cms.block.purchases }
            - { position: right, type: maxim_cms.block.latest_purchases }

# HTML PURIFIER
exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'
        Filter.YouTube: true
        HTML.SafeIframe: true
        URI.SafeIframeRegexp: "#^(https?:)?//(www\.youtube(?:-nocookie)?\.com/embed/|player\.vimeo\.com/video/)#"

# MAXIM CMS
maxim_cms:
   store:
       email: purchases@eyeofender.com
       paypal: https://www.paypal.com/cgi-bin/webscr
       #paypal: https://sandbox.paypal.com/cgi-bin/webscr
       currency: GBP #his can be any 3 letter ISO 4217 code
       currency_symbol: £
       return: http://themassmc.com/shop
       cancel: http://themassmc.com/shop/sorry.html
       ipn: http://themassmc.com/shop/ipn/paypal
   register:
      mail:
         enabled: true
         subject: Welcome to our website
         message: Our server ip is: hub.eyeofender.com have fun playing!
      validation: #Requires the user to validate it's email before registering
         enabled: true
         salt: uzegfuiqp #Security code, this can be anything, prefer numbers and letters
         time: 864000 #Time they get before the validation key expires, default 10 days
         subject: Validate your website account now!
         message: Please validate your website account by following the link beneath
   server:
       name: EyeofEnder
       ip: hub.eyeofender.com
       mysql:
           host: %server.mysql.host%
           user: %server.mysql.user%
           pass: %server.mysql.pass%
           db: %server.mysql.db%
   general:
      default_role: Member
      domain: http://eyeofender.com/
      maintenance: true
   emails:
      info: info@eyeofender.com
      support: support@eyeofender.com
   pages:
      forum:  http://eyeofender.com/forum
   account:
      #Salt code for your unique minecraft code,
      #used to validate ingame user accounts when linking a minecraft acccount to a website account,
      #should be the same as in the jar
      codeSalt: f4uarQzr2ZZC9g6g5t3NV
      codeLength: 5
      send:
         enabled: true
         command: pex user {USER} group add Member
   forgotPassword:
      #Salt for the forgot password function, SECURITY precaution
      salt: HTWgMJcfyb7QjyDqvcdD6ZbD
      #Time for how long the reset url should be valid, in seconds
      time: 3600
maxim_module_forum:
   threads:
       threshold: 3 # in minutes
   posts:
       threshold: 1 # in minutes

# app/config/config.yml
jms_security_extra:
    # Enables expression language
    expressions: true