security:
    access_decision_manager:
        # strategy can be: affirmative, unanimous or consensus
        strategy: unanimous
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha1
            encode_as_base64: false
            iterations: 0

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        default:
            entity: { class: Maxim\CMSBundle\Entity\User, property: username } # This is an ORM entity and username is just the username property of the entity.
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                #success_handler: authentication_handler
                #failure_handler: authentication_handler
            remember_me:
                key: %secret%
                lifetime: 31536000
                path: ~
                domain: ~
                always_remember_me: true
            security: true
            logout:       true
            anonymous:    true
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_STAFF }
        - { path: ^/shop/ipn/paypal, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/shop/step, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/shop/confirm, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/application, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/account, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/forum, access: "isAnonymous() || !hasRole('ROLE_BANNED')" }


