security:
    access_decision_manager:
        # strategy can be: affirmative, unanimous or consensus
        strategy: unanimous
    encoders:
        "Maxim\CMSBundle\Entity\User": { algorithm: sha1, encode_as_base64: false, iterations: 0 }   # You'll set this to sha1 when you have everything working.

    providers:
        default:    
            entity: { class: Maxim\CMSBundle\Entity\User, property: username } # This is an ORM entity and username is just the username property of the entity.
    role_hierarchy:
        ROLE_MEMBER: ROLE_GUEST
        ROLE_STAFF: ROLE_MEMBER
        ROLE_ADMIN: ROLE_STAFF

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path:  /login
                check_path:  /login_check
                success_handler: authentication_handler
                failure_handler: authentication_handler
                use_referer: true
                default_target_path: /
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
                always_remember_me: true
            logout: 
                path: /logout
                target: /

    access_control:
      - { path: ^/admin, roles: ROLE_STAFF }
      - { path: ^/admin2, roles: ROLE_STAFF }
      - { path: ^/members, roles: ROLE_MEMBER }
      - { path: ^/shop/ipn/paypal, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/shop/step, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/shop/confirm, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/application, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/account, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      #- { path: ^/foo, access: "hasRole('FOO') and hasRole('BAR')" }
      #- { path: ^/forum, access: "!hasRole('ROLE_BANNED')"}
