maxim_cms:
   general:
      default_role: Member
      domain: http://mcthefridge.com/
      maintenance: true
   emails:
      info: info@mcthefridge.com
      support: support@mcthefridge.com
   pages:
      forum:  http://forum.mcthefridge.com
   server:
      name: mcthefridge
      ip: server.mcthefridge.com
      mysql:
         host: 198.245.49.34
         user: root
         pass: T1h823S3368c30D
         db: mc1360
   account:
      #Salt code for your unique minecraft code,
      #used to validate ingame user accounts when linking a minecraft acccount to a website account,
      #should be the same as in the jar
      codeSalt: f4uarQzr2ZZC9g6g5t3NV
      codeLength: 5
      send:
         enabled: true
         command: pex user {USER} group add Member
   forgotPassword:
      #Salt for the forgot password function, SECURITY precaution
      salt: HTWgMJcfyb7QjyDqvcdD6ZbD
      #Time for how long the reset url should be valid, in seconds
      time: 3600
      emailFrom: info@mcthefridge.com
   register:
      mail:
         enabled: true
         subject: Welcome to our website
         message: Our server ip is: hub.mcthefridge.com have fun playing!
      validation: #Requires the user to validate it's email before registering
         enabled: true
         salt: uzegfuiqp #Security code, this can be anything, prefer numbers and letters
         time: 864000 #Time they get before the validation key expires, default 10 days
         subject: Validate your website account now!
         message: Please validate your website account by following the link beneath
#   admin:
#      ban:
#      command: ban {USER} {REASON}
#      webgroup: 99 #ID of the website banned rank
#   tempban:
#      command: tempban {USER} {TIME} {REASON}
#   unban:
#      command: unban {USER}
#   cache:
#      statistics: 600 #in seconds
#      news: 3600
#      pages:
#         landing: 3600
#      navigation:
#         other: 3600