#admin_application
admin_application:
  path: /admin/application
  defaults: { _controller: MaximModuleApplicationBundle:Admin:application }
admin_application_ajax:
  path: /admin/application/open/ajax
  defaults: { _controller: MaximModuleApplicationBundle:Admin:applicationList }
admin_application_accepted_ajax:
  path: /admin/application/accepted/ajax
  defaults: { _controller: MaximModuleApplicationBundle:Admin:applicationAcceptedList }
admin_application_delete:
  path: /admin/application/delete
  defaults: { _controller: MaximModuleApplicationBundle:Admin:application }
admin_application_view:
  path: /admin/application/view/{id}
  defaults: { _controller: MaximModuleApplicationBundle:Admin:viewApplication }
admin_application_deny:
  path: /admin/application/deny
  defaults: { _controller: MaximModuleApplicationBundle:Admin:applicationDeny }
admin_application_accept:
  path: /admin/application/accept
  defaults: { _controller: MaximModuleApplicationBundle:Admin:applicationAccept }
admin_application_add:
  path: /admin/application/add
  defaults: { _controller: MaximModuleApplicationBundle:Admin:applicationAddView }
admin_application_add_ajax:
  path: /admin/application/ajax/add
  defaults: { _controller: MaximModuleApplicationBundle:Admin:applicationAdd }
admin_application_reply:
  path: /admin/application/reply/ajax
  defaults: { _controller: MaximModuleApplicationBundle:Admin:applicationReply }

application_create:
  path: /admin/application/create
  defaults: { _controller: MaximModuleApplicationBundle:Admin:applicationCreate }