#application
application_action:
  path: /application/add
  defaults: { _controller: MaximModuleApplicationBundle:Application:add }
application:
  path: /application/{id}-{name}
  defaults: { _controller: MaximModuleApplicationBundle:Application:view }
server_pattern:
  path: /server
application_account:
  path: /account/applications
  defaults: { _controller: MaximModuleApplicationBundle:Application:account }
application_reply:
  path: /account/application/reply
  defaults: { _controller: MaximModuleApplicationBundle:Application:reply }
application_view:
  path: /account/application/{id}-{name}
  defaults: { _controller: MaximModuleApplicationBundle:Application:accountView }
application_view_pattern:
  path: /account/application
applications_list:
  path: /applications
  defaults: { _controller: MaximModuleApplicationBundle:Application:list }

