forum_main:
  path: /
  defaults: { _controller: MaximModuleForumBundle:Default:load }
forum_view:
  path: /{id}/{seo}
  defaults: { _controller: MaximModuleForumBundle:Default:forumView }


##################
# THREAD ACTIONS
##################
forum_thread_create:
  path: /{id}/thread/create
  defaults: { _controller: MaximModuleForumBundle:Thread:create }
forum_thread_view:
  path: /{id}/thread/{threadid}
  defaults: { _controller: MaximModuleForumBundle:Thread:view }
forum_thread_edit:
  path: /{id}/thread/{threadid}/edit
  defaults: { _controller: MaximModuleForumBundle:Thread:edit }

forum_thread_pin_ajax:
  path: /admin/thread/{id}/pin/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:adminPinAjax }
forum_thread_lock_ajax:
  path: /admin/thread/{id}/lock/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:adminLockAjax }
forum_thread_archive_ajax:
  path: /admin/thread/{id}/archive/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:adminArchiveAjax }
forum_thread_move_ajax:
  path: /admin/thread/{id}/move/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:adminMoveAjax }

################
# THREAD POSTS
################
forum_thread_reply_ajax:
  path: /{id}/thread/{threadid}/reply/action
  defaults: { _controller: MaximModuleForumBundle:Post:reply }


###############
# POST ACTIONS
###############
forum_post_like_ajax:
  path: /post/{id}/like/ajax
  defaults: { _controller: MaximModuleForumBundle:Post:likeAjax }
forum_post_edit:
  path: /{id}/thread/{threadid}/post/{postid}/edit
  defaults: { _controller: MaximModuleForumBundle:Post:edit }