forum_main:
  pattern: /
  defaults: { _controller: MaximModuleForumBundle:Default:load }
forum_view:
  pattern: /{id}
  defaults: { _controller: MaximModuleForumBundle:Default:forumView }


##################
# THREAD ACTIONS
##################
forum_thread_create_ajax:
  pattern: /{id}/thread/create/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:createAjax }
forum_thread_create:
  pattern: /{id}/thread/create
  defaults: { _controller: MaximModuleForumBundle:Thread:create }
forum_thread_view:
  pattern: /{id}/thread/{threadid}
  defaults: { _controller: MaximModuleForumBundle:Thread:view }
forum_thread_edit_ajax:
  pattern: /{id}/thread/{threadid}/edit/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:editAjax }
forum_thread_edit:
  pattern: /{id}/thread/{threadid}/edit
  defaults: { _controller: MaximModuleForumBundle:Thread:edit }

forum_thread_pin_ajax:
  pattern: /admin/thread/{id}/pin/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:adminPinAjax }
forum_thread_lock_ajax:
  pattern: /admin/thread/{id}/lock/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:adminLockAjax }
forum_thread_archive_ajax:
  pattern: /admin/thread/{id}/archive/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:adminArchiveAjax }
forum_thread_move_ajax:
  pattern: /admin/thread/{id}/move/ajax
  defaults: { _controller: MaximModuleForumBundle:Thread:adminMoveAjax }

################
# THREAD POSTS
################
forum_thread_reply_ajax:
  pattern: /{id}/thread/{threadid}/reply/action
  defaults: { _controller: MaximModuleForumBundle:Post:reply }


###############
# POST ACTIONS
###############
forum_post_like_ajax:
  pattern: /post/{id}/like/ajax
  defaults: { _controller: MaximModuleForumBundle:Post:likeAjax }
forum_post_edit_ajax:
  pattern: /{id}/thread/{threadid}/post/{postid}/edit/ajax
  defaults: { _controller: MaximModuleForumBundle:Post:editAjax }
forum_post_edit:
  pattern: /{id}/thread/{threadid}/post/{postid}/edit
  defaults: { _controller: MaximModuleForumBundle:Post:edit }