########
# ADMIN
########
admin_forum:
  path: /
  defaults: { _controller: MaximModuleForumBundle:AdminForum:view }

# admin - recache
admin_forum_recache:
   path: /recache
   defaults: { _controller: MaximModuleForumBundle:Admin:recache }