doctrine:
    dbal:
      default_connection: default
      connections:
        tickets:
          driver:   "pdo_mysql"
          host:     "%127.0.0.1"
          port:     "3306"
          dbname:   "test2"
          user:     "root"
          password: "lvsdev1410"
          charset:  UTF8

    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                metadata_cache_driver: apc
                query_cache_driver: apc
                result_cache_driver: apc
                mappings:
                    MaximModuleTicketBundle: ~
            customer:
                connection:       server