tickets_index:
  pattern: /account/tickets
  defaults: { _controller: MaximModuleTicketBundle:Ticket:index }
ticket_create:
  pattern: /account/ticket/create
  defaults: { _controller: MaximModuleTicketBundle:Ticket:create }
ticket_view:
  pattern: /account/ticket/view/{id}
  defaults: { _controller: MaximModuleTicketBundle:Ticket:viewTicket }
ticket_view_pattern:
  pattern: /account/ticket/view
ticket_reply:
  pattern: /account/ticket/reply
  defaults: { _controller: MaximModuleTicketBundle:Ticket:reply }
ticket_close:
  pattern: /account/ticket/close
  defaults: { _controller: MaximModuleTicketBundle:Ticket:close }
ticket_open:
  pattern: /account/ticket/open
  defaults: { _controller: MaximModuleTicketBundle:Ticket:open }
