services:
    sonata.admin.announcement:
        class: Maxim\CMSBundle\Admin\AnnouncementAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Announcements", icon: "fa-flask", bg: "bg-warning" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\Announcement
            - ~
        calls:
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]

    sonata.admin.page:
        class: Maxim\CMSBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Pages" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\Page
            - ~
        calls:
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]
    sonata.admin.store.items:
        class: Maxim\CMSBundle\Admin\StoreItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Store items" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\StoreItem
            - ~
        calls:
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]
            - [ setConfigs, [%maxim_cms.store%]]
    sonata.admin.store.categories:
        class: Maxim\CMSBundle\Admin\StoreCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Store categories" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\StoreCategory
            - ~
        calls:
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]
    sonata.admin.server:
        class: Maxim\CMSBundle\Admin\ServerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Servers" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\Server
            - ~
    sonata.admin.vote:
        class: Maxim\CMSBundle\Admin\VoteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Vote sites" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\Vote
            - ~
    sonata.admin.serverips:
        class: Maxim\CMSBundle\Admin\ServerIpAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Server ips" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\ServerIp
            - ~
    sonata.admin.nodes:
        class: Maxim\CMSBundle\Admin\CoreNodeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Nodes" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\CoreNode
            - ~
        calls:
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]
    sonata.admin.user:
        class: Maxim\CMSBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Users" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\User
            - ~
        calls:
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]
    sonata.admin.purchase:
        class: Maxim\CMSBundle\Admin\PurchaseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Purchases" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\Purchase
            - ~
        calls:
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]

    # ---------
    #   FORUM
    # ---------
    sonata.admin.forum.category:
        class: Maxim\Module\ForumBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "Categories" }
        arguments:
            - ~
            - Maxim\Module\ForumBundle\Entity\Category
            - ~
        calls:
            - [ setSecurityContext, [@security.context]]
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]
    sonata.admin.forum.forum:
        class: Maxim\Module\ForumBundle\Admin\ForumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "Forums" }
        arguments:
            - ~
            - Maxim\Module\ForumBundle\Entity\Forum
            - ~
        calls:
            - [ setSecurityContext, [@security.context]]
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]
    sonata.admin.forum.thread:
         class: Maxim\Module\ForumBundle\Admin\ThreadAdmin
         tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "Threads" }
         arguments:
            - ~
            - Maxim\Module\ForumBundle\Entity\Thread
            - ~
         calls:
            - [ setSecurityContext, [@security.context]]
            - [ setDoctrine, [@doctrine.orm.entity_manager]]
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]
    sonata.admin.forum.post:
         class: Maxim\Module\ForumBundle\Admin\PostAdmin
         tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "Posts" }
         arguments:
            - ~
            - Maxim\Module\ForumBundle\Entity\Post
            - ~
    sonata.admin.forum.award:
        class: Maxim\Module\ForumBundle\Admin\AwardAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Forum", label: "Awards" }
        arguments:
            - ~
            - Maxim\CMSBundle\Entity\Award
            - ~

    # ---------------
    #   APPLICATION
    # ---------------
    sonata.admin.module.applicationForms:
         class: Maxim\Module\ApplicationBundle\Admin\ApplicationFormAdmin
         tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Application forms" }
         arguments:
            - ~
            - Maxim\Module\ApplicationBundle\Entity\Application
            - "MaximModuleApplicationBundle:Admin"
         calls:
            - [ setSecurityContext, [@security.context]]
            - [ setTemplate, [edit, MaximModuleApplicationBundle:Admin:createApplication.html.twig]]
    sonata.admin.module.applicationUser:
         class: Maxim\Module\ApplicationBundle\Admin\ApplicationUserAdmin
         tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Applications" }
         arguments:
            - ~
            - Maxim\Module\ApplicationBundle\Entity\UserApplication
            - "MaximModuleApplicationBundle:Admin"
         calls:
            - [ setSecurityContext, [@security.context]]
            - [ setTemplate, [edit, MaximModuleApplicationBundle:Admin:viewApplication.html.twig]]
            - [ addChild, [ @sonata.admin.module.application.replies ] ]
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]
    sonata.admin.module.application.replies:
         class: Maxim\Module\ApplicationBundle\Admin\ApplicationReplyAdmin
         tags:
            - { name: sonata.admin, manager_type: orm, group: "Application", label: "Application replies" }
         arguments:
            - ~
            - Maxim\Module\ApplicationBundle\Entity\ApplicationReply
            - ~
         calls:
            - [ setSecurityContext, [@security.context]]
            - [ setEntityManager, [@doctrine.orm.entity_manager]]
            - [ setTemplate, [inner_list_row, MaximModuleApplicationBundle:Admin:inner_row_application.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]

    # ---------
    #  TICKETS
    # ---------
    sonata.admin.module.ticket:
         class: Maxim\Module\TicketBundle\Admin\TicketAdmin
         tags:
            - { name: sonata.admin, manager_type: orm, group: "Ticket", label: "Tickets" }
         arguments:
            - ~
            - Maxim\Module\TicketBundle\Entity\UserTicket
            - "MaximModuleTicketBundle:Admin"
         calls:
            - [ setSecurityContext, [@security.context]]
            - [ setTemplate, [inner_list_row, MaximModuleTicketBundle:Admin:inner_row_ticket.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]
            - [ setTemplate, [edit, MaximModuleTicketBundle:Admin:viewTicket.html.twig]]
            - [ addChild, [ @sonata.admin.module.ticket.replies ] ]
    sonata.admin.module.ticket.replies:
         class: Maxim\Module\TicketBundle\Admin\TicketReplyAdmin
         tags:
            - { name: sonata.admin, manager_type: orm, group: "Ticket", label: "Ticket replies" }
         arguments:
            - ~
            - Maxim\Module\TicketBundle\Entity\TicketReply
            - "MaximModuleTicketBundle:AdminReply"
         calls:
            - [ setSecurityContext, [@security.context]]
            - [ setEntityManager, [@doctrine.orm.entity_manager]]
            - [ setTemplate, [inner_list_row, MaximModuleTicketBundle:Admin:inner_row_ticketreply.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]
            - [ setTemplate, [edit, MaximCMSBundle:AdminSonata:edit.html.twig]]

    sonata.admin.module.ticketForm:
         class: Maxim\Module\TicketBundle\Admin\TicketFormAdmin
         tags:
            - { name: sonata.admin, manager_type: orm, group: "Ticket", label: "Ticket forms" }
         arguments:
            - ~
            - Maxim\Module\TicketBundle\Entity\Ticket
            - "MaximModuleTicketBundle:Admin"
         calls:
            - [ setSecurityContext, [@security.context]]
            - [ setTemplate, [edit, MaximModuleTicketBundle:Admin:createApplication.html.twig]]