security:
    role_hierarchy:
    #LIST: view the list of objects
    #VIEW: view the detail of one object
    #CREATE: create a new object
    #EDIT: update an existing object
    #DELETE: delete an existing object
    #EXPORT (for the native Sonata export links)

    #ROLE_SONATA_..._GUEST
    #a guest that is allowed to VIEW an object and a LIST of objects;

    #ROLE_SONATA_..._STAFF
    #probably the biggest part of the users, a staff user has the same permissions as guests and is additionally allowed to EDIT and CREATE new objects;

    #ROLE_SONATA_..._EDITOR
    #an editor is granted all access and, compared to the staff users, is allowed to DELETE;

    #ROLE_SONATA_..._ADMIN
    #an administrative user is granted all access and on top of that, the user is allowed to grant other users access.

        ROLE_SONATA_ADMIN_ANNOUNCEMENT_STAFF:
            - ROLE_SONATA_ADMIN_ANNOUNCEMENT_LIST
            - ROLE_SONATA_ADMIN_ANNOUNCEMENT_VIEW
            - ROLE_SONATA_ADMIN_ANNOUNCEMENT_CREATE
            - ROLE_SONATA_ADMIN_ANNOUNCEMENT_EDIT
            - ROLE_SONATA_ADMIN_ANNOUNCEMENT_DELETE

        ROLE_SONATA_ADMIN_FORUM_CATEGORY_STAFF:
            - ROLE_SONATA_ADMIN_FORUM_CATEGORY_LIST
            - ROLE_SONATA_ADMIN_FORUM_CATEGORY_VIEW
            - ROLE_SONATA_ADMIN_FORUM_CATEGORY_CREATE
            - ROLE_SONATA_ADMIN_FORUM_CATEGORY_EDIT
            #- ROLE_SONATA_ADMIN_FORUM_CATEGORY_DELETE

        ROLE_SONATA_ADMIN_FORUM_FORUM_STAFF:
            - ROLE_SONATA_ADMIN_FORUM_FORUM_LIST
            - ROLE_SONATA_ADMIN_FORUM_FORUM_VIEW
            - ROLE_SONATA_ADMIN_FORUM_FORUM_CREATE
            - ROLE_SONATA_ADMIN_FORUM_FORUM_EDIT
            #- ROLE_SONATA_ADMIN_FORUM_FORUM_DELETE

        ROLE_SONATA_ADMIN_FORUM_THREAD_STAFF:
            - ROLE_SONATA_ADMIN_FORUM_THREAD_LIST
            - ROLE_SONATA_ADMIN_FORUM_THREAD_VIEW
            - ROLE_SONATA_ADMIN_FORUM_THREAD_CREATE
            - ROLE_SONATA_ADMIN_FORUM_THREAD_EDIT
            - ROLE_SONATA_ADMIN_FORUM_THREAD_DELETE

        ROLE_SONATA_ADMIN_FORUM_POST_STAFF:
            - ROLE_SONATA_ADMIN_FORUM_POST_LIST
            - ROLE_SONATA_ADMIN_FORUM_POST_VIEW
            - ROLE_SONATA_ADMIN_FORUM_POST_CREATE
            - ROLE_SONATA_ADMIN_FORUM_POST_EDIT
            - ROLE_SONATA_ADMIN_FORUM_POST_DELETE

        ROLE_SONATA_ADMIN_MODULE_APPLICATIONFORMS_STAFF:
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONFORMS_LIST
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONFORMS_VIEW
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONFORMS_CREATE
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONFORMS_EDIT
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONFORMS_DELETE

        ROLE_SONATA_ADMIN_MODULE_APPLICATIONUSER_STAFF:
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONUSER_LIST
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONUSER_VIEW
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONUSER_CREATE
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONUSER_EDIT
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONUSER_DELETE

        ROLE_SONATA_ADMIN_MODULE_APPLICATION_REPLIES_STAFF:
            - ROLE_SONATA_ADMIN_MODULE_APPLICATION_REPLIES_LIST
            - ROLE_SONATA_ADMIN_MODULE_APPLICATION_REPLIES_VIEW
            - ROLE_SONATA_ADMIN_MODULE_APPLICATION_REPLIES_CREATE
            - ROLE_SONATA_ADMIN_MODULE_APPLICATION_REPLIES_EDIT
            - ROLE_SONATA_ADMIN_MODULE_APPLICATION_REPLIES_DELETE

        ROLE_SONATA_ADMIN_MODULE_TICKET_STAFF:
            - ROLE_SONATA_ADMIN_MODULE_TICKET_LIST
            - ROLE_SONATA_ADMIN_MODULE_TICKET_VIEW
            - ROLE_SONATA_ADMIN_MODULE_TICKET_CREATE
            - ROLE_SONATA_ADMIN_MODULE_TICKET_EDIT
            - ROLE_SONATA_ADMIN_MODULE_TICKET_DELETE

        ROLE_SONATA_ADMIN_MODULE_TICKET_REPLIES_DEV:
            - ROLE_SONATA_ADMIN_MODULE_TICKET_REPLIES_LIST
            - ROLE_SONATA_ADMIN_MODULE_TICKET_REPLIES_VIEW
            - ROLE_SONATA_ADMIN_MODULE_TICKET_REPLIES_CREATE
            - ROLE_SONATA_ADMIN_MODULE_TICKET_REPLIES_EDIT
            - ROLE_SONATA_ADMIN_MODULE_TICKET_REPLIES_DELETE

        ROLE_SONATA_ADMIN_STORE_ITEMS_STAFF:
            - ROLE_SONATA_ADMIN_STORE_ITEMS_LIST
            - ROLE_SONATA_ADMIN_STORE_ITEMS_VIEW
            - ROLE_SONATA_ADMIN_STORE_ITEMS_CREATE
            - ROLE_SONATA_ADMIN_STORE_ITEMS_EDIT
            - ROLE_SONATA_ADMIN_STORE_ITEMS_DELETE

        ROLE_SONATA_ADMIN_STORE_CATEGORIES_STAFF:
            - ROLE_SONATA_ADMIN_STORE_CATEGORIES_LIST
            - ROLE_SONATA_ADMIN_STORE_CATEGORIES_VIEW
            - ROLE_SONATA_ADMIN_STORE_CATEGORIES_CREATE
            - ROLE_SONATA_ADMIN_STORE_CATEGORIES_EDIT
            - ROLE_SONATA_ADMIN_STORE_CATEGORIES_DELETE

        ROLE_SONATA_STAFF:
            - ROLE_SONATA_ADMIN_ANNOUNCEMENT_STAFF
            - ROLE_SONATA_ADMIN_FORUM_CATEGORY_STAFF
            - ROLE_SONATA_ADMIN_FORUM_FORUM_STAFF
            - ROLE_SONATA_ADMIN_FORUM_THREAD_STAFF
            - ROLE_SONATA_ADMIN_FORUM_POST_STAFF
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONFORMS_STAFF
            - ROLE_SONATA_ADMIN_MODULE_APPLICATIONUSER_STAFF
            - ROLE_SONATA_ADMIN_MODULE_APPLICATION_REPLIES_STAFF
            - ROLE_SONATA_ADMIN_MODULE_TICKET_STAFF
            - ROLE_SONATA_ADMIN_MODULE_TICKET_REPLIES_STAFF

        ROLE_MEMBER: ROLE_GUEST
        ROLE_STAFF: [ROLE_MEMBER, ROLE_SONATA_STAFF]
        ROLE_DEV:
            - ROLE_STAFF
            - ROLE_SONATA_ADMIN_STORE_ITEMS_STAFF
            - ROLE_SONATA_ADMIN_STORE_CATEGORIES_STAFF
        ROLE_ADMIN: [ROLE_STAFF, ROLE_ALLOWED_TO_SWITCH, ROLE_SUPER_ADMIN, ROLE_SONATA_ADMIN]