#-------
# PAGES
#-------
#normal
default:
   path: /
   defaults: { _controller: MaximCMSBundle:Default:index }
home:
  path: /home
  defaults: { _controller: MaximCMSBundle:Default:index }
news_comments:
  path: /news/{newsId}
  defaults: { _controller: MaximCMSBundle:Default:post }
news:
  path: /news
  defaults: { _controller: MaximCMSBundle:Default:news }
commentAction:
  path: /news/add
  defaults: { _controller: MaximCMSBundle:Default:add }
  requirements:
     key: ".+"
news_comments:
  path: /news/{newsId}
  defaults: { _controller: MaximCMSBundle:Default:post }

register:
  path: /register
  defaults: { _controller: MaximCMSBundle:Security:registerView }
register_validation:
  path: /validate/{key}
  defaults: { _controller: MaximCMSBundle:Security:validate }
  requirements:
     key: ".+"

#vote
topvoters:
  path: /module/topvoters
  defaults: { _controller: MaximCMSBundle:Module/Vote/Vote:topVoters }
#-------
# SHOP
#-------
shop:
  path: /shop
  defaults: { _controller: MaximCMSBundle:Store:index }
shop_step2:
  path: /shop/step/2
  defaults: { _controller: MaximCMSBundle:Store:step2 }
shop_confirm:
  path: /shop/confirm
  defaults: { _controller: MaximCMSBundle:Store:confirm }
shop_finish:
  path: /shop/finish
  defaults: { _controller: MaximCMSBundle:Store:finish }
shop_purchase_history:
  path: /account/purchase/history
  defaults: { _controller: MaximCMSBundle:Store:purchaseHistory }
#Ipn's
ipn_paypal:
  path: /shop/ipn/paypal
  defaults: { _controller: MaximCMSBundle:Ipn/IpnPaypal:paypal }
ipn_paypal:
  path: /shop/ipn/bitpay
  defaults: { _controller: MaximCMSBundle:Ipn:bitpayIpn }
paypal_done:
  path: /shop/complete
  defaults: { _controller: MaximCMSBundle:Store:complete }

#---------
# MEMBERS
#---------
profile:
  path: /profile/{name}
  defaults: { _controller: MaximCMSBundle:Profile:view }
profile_friend_request_ajax:
  path: /friend/add/ajax
  defaults: { _controller: MaximCMSBundle:Profile:sendFriendRequest }
profile_friend_delete_ajax:
  path: /friend/delete/ajax
  defaults: { _controller: MaximCMSBundle:Profile:deleteFriend }
profile_friend_requests:
  path: /account/friends/requests
  defaults: { _controller: MaximCMSBundle:Profile:viewFriendrequests }
profile_friendrequest_approve_ajax:
  path: /account/friend/request/approve
  defaults: { _controller: MaximCMSBundle:Profile:friendRequest, type: approve }
  methods: [POST]
profile_friendrequest_ignore_ajax:
  path: /account/friend/request/ignore
  defaults: { _controller: MaximCMSBundle:Profile:friendRequest, type: ignore }
  methods: [POST]
account:
  path: /account
  defaults: { _controller: MaximCMSBundle:Account:index }
account_default:
  path: /account/profile
  defaults: { _controller: MaximCMSBundle:Account:accountView }
account_profile_save:
  path: /account/profile/save
  defaults: { _controller: MaximCMSBundle:Account:accountSave }
  requirements:
    _method: POST
login:
    pattern:   /login
    defaults:  { _controller: MaximCMSBundle:Security:login } # Where ViewSubDir is a folder in the views directory of your bundle. And, where login is your controller action.
#loginForm:
#    pattern:   /login
#    defaults:  { _controller: MaximCMSBundle:Security:loginForm } # Where ViewSubDir is a folder in the views directory of your bundle. And, where login is your controller action.
#login_check:
#    pattern:   /login_check
#    requirements:
#        _method:  POST
logout:
  path: /logout
reset:
  path: /reset
  defaults: { _controller: MaximCMSBundle:Security:reset }
members:
    pattern:   /members
    defaults:  { _controller: MaximCMSBundle:Security:members }  #where members is your controller action. (This is the place you defined in the security.yml file)
account_change_password:
  path: /account/password/change
  defaults: { _controller: MaximCMSBundle:Security:changePassView }

#Forgot password
account_forgot_password_send:
  path: /forgot/send
  defaults: { _controller: MaximCMSBundle:Security:forgotPassSend }
account_forgot_password_reset:
  path: /forgot/{key}
  defaults: { _controller: MaximCMSBundle:Security:forgotPass }
  requirements:
     key: ".+"
account_forgot_password:
  path: /forgot
  defaults: { _controller: MaximCMSBundle:Security:forgotPassView }

#mincraft accounts
#account_minecraft:
#  path: /account/minecraft
#  defaults: { _controller: MaximCMSBundle:Account:minecraftView }
account_minecraft_add:
  path: /account/minecraft/add
  defaults: { _controller: MaximCMSBundle:Account:Add }
portret:
  path: /portret/{char}
  defaults: { _controller: MaximCMSBundle:Minecraft:renderChar }

#--------
# SERVER
#--------

server_view:
  path: /server
  defaults: { _controller: MaximCMSBundle:Module/Server/Server:index }
  requirements:
    _method: _POST
server_online_players:
  path: /server/online
  defaults: { _controller: MaximCMSBundle:Server:online }

#profile
profile_friend_add:
  path: /profile/{username}/add
  defaults: { _controller: MaximCMSBundle:Account:friendAdd }
profile_friend_delete:
  path: /profile/{username}/delete/{friend}
  defaults: { _controller: MaximCMSBundle:Account:friendDelete }
profile_load_content:
  path: /profile/{username}/ajax
  defaults: { _controller: MaximCMSBundle:Account:profileAjax }
  requirements:
     username: ".+"


#------
# AJAX
#------
ajax_register_action:
  path: /register_action
  defaults: { _controller: MaximCMSBundle:Security:register }
#ajax_login:
#    pattern:   /ajax_login
#    defaults:  { _controller: MaximCMSBundle:Security:ajaxLogin } # Where ViewSubDir is a folder in the views directory of your bundle. And, where login is your controller action.
ajax_shoutbox:
  path: /module/shoutbox/add
  defaults: { _controller: MaximCMSBundle:Module/Shout/Shout:shout }
ajax_shoutbox_load:
  path: /module/shoutbox/load
  defaults: { _controller: MaximCMSBundle:Module/Shout/Shout:shoutLoad }
ajax_poll_load:
  path: /module/poll/load
  defaults: { _controller: MaximCMSBundle:Module/Poll/Poll:pollLoad }
ajax_poll:
  path: /module/poll/vote
  defaults: { _controller: MaximCMSBundle:Module/Poll/Poll:pollVote }
ajax_poll_results:
  path: /module/poll/results
  defaults: { _controller: MaximCMSBundle:Module/Poll/Poll:pollResult }
ajax_password_change:
  path: /account/password/change/action
  defaults: { _controller: MaximCMSBundle:Security:changePass }
  requirements:
     _method: POST
ajax_visitor:
  path: /statistic/visitor
  defaults: { _controller: MaximCMSBundle:Statistic:visitor }
  requirements:
    _method: POST
#staff
staff:
  path: /staff
  defaults: { _controller: MaximCMSBundle:Module/Staff/Staff:view }
#-------
# PAGES
#-------
#page_forum:
#  path: /forum
#  defaults: { _controller: MaximCMSBundle:Page:forum }
#custom page
page_custom:
  path: /page/{page}
  defaults: { _controller: MaximCMSBundle:Page:renderPage }
  requirements:
     page: ".+"
page_staff:
  path: /module/staff/load
  defaults: { _controller: MaximCMSBundle:Module/Staff/Staff:view }

page_clan:
  path: /page/clan/{clan}
  defaults: {_controller: MaximCMSBundle:Module/Clan/Clan:view }

admin_shop_resend:
  path: /admin/shop/resend
  defaults: { _controller: MaximCMSBundle:Admin:resendPurchase }
CMS_DEFAULT_HOME:
  path: /
  defaults: { _controller: MaximCMSBundle:Default:index }
# note routes to create new users are not here but you'll need to create them just like you would any other route.
# I left them out here because this is just meant to get you up and running as simply as possible (That at it will take me longer to type all this up... LOL)