services:
#    maxim_cms.example:
#        class: %maxim_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
   # CONTROLLERS
    maxim_cms.controller.exception_controller:
        parent: twig.controller.exception
        class: Maxim\CMSBundle\Controller\ExceptionController
   # TYPES
    maxim_cms_user.profile.form.type:
        class: Maxim\CMSBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: maxim_cms_user_profile }
    maxim_cms_user.registration.form.type:
        class: Maxim\CMSBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: maxim_cms_user_registration }
   # HELPERS
    maxim_cms.rest.helper:
        class: Maxim\CMSBundle\Helper\RESTHelper
        arguments: [@logger]

    maxim_cms.logger:
        class: Symfony\Bridge\Monolog\Logger

    my_service:
        class: Monolog\Logger
        arguments: [@logger]
        tags:
            - { name: monolog.logger, channel: server }
    friend.twig.extension:
        class: Maxim\CMSBundle\Twig\Extension\FriendExtension
        tags:
            - { name: twig.extension }
        arguments: [@doctrine, @security.context]
    minecraft.helper:
        class: Maxim\CMSBundle\Helper\MinecraftHelper
        arguments: [ @logger, @maxim_cms.rest.helper ]
    account.helper:
        class: Maxim\CMSBundle\Helper\AccountHelper
        arguments: [ @service_container, @doctrine, @security.context ]
    bbcode.helper:
        class: Maxim\CMSBundle\Helper\BbcodeHelper
    security.helper:
        class: Maxim\CMSBundle\Helper\SecurityHelper
        arguments: [ @service_container, @doctrine, @security.context ]
    statistic.helper:
        class: Maxim\CMSBundle\Helper\StatisticHelper
        arguments: [ @doctrine.orm.entity_manager ]
    module.helper:
        class: Maxim\CMSBundle\Helper\ModuleHelper
        arguments: [ @service_container, @security.context ]
    purchase.helper:
        class: Maxim\CMSBundle\Helper\PurchaseHelper
        arguments: [ @doctrine.orm.entity_manager, @logger ]
    maxim_cms.deliver.helper:
        class: Maxim\CMSBundle\Helper\DeliverHelper
        arguments: [ @event_dispatcher, @minecraft.helper, @doctrine.orm.entity_manager, @logger, %mysql%]

# LISTENERS
    exception.listener:
        class: Maxim\CMSBundle\Listeners\ExceptionListener
        arguments: [@logger, @templating, @security.context]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    maxim_cms.configure_menu_listener:
        class: Maxim\CMSBundle\Listeners\MenuListener
        arguments: [@logger, @service_container]
        tags:
            - { name: kernel.event_listener, event: 'maxim_cms.event_menu', method: configureMenu}
    maxim_cms.action.store_notification:
        class: Maxim\CMSBundle\Action\StoreNotificationAction
        arguments: [ @doctrine.orm.entity_manager, @logger, @purchase.helper, @event_dispatcher, @maxim_cms.deliver.helper]

    maxim_cms.oneupload.listener:
        class: Maxim\CMSBundle\EventListener\UploadListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
# VALIDATORS
    maxim_cms.validator.minecraft:
        class: Maxim\CMSBundle\Component\Validator\ValidMinecraftValidator
        tags:
            - { name: validator.constraint_validator, alias: maxim_cms_validator_minecraft }
        calls:
            - [ setMinecraftHelper, [@minecraft.helper]]
# BLOCKS
    maxim_cms.block.latest_users:
        public: true
        class: Maxim\CMSBundle\Block\LatestUsersBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - "maxim_cms.block.latest_users"
            - @templating
        calls:
            - [ setUserManager, [@maxim_cms.manager.user]]

    maxim_cms.block.latest_purchases:
        public: true
        class: Maxim\CMSBundle\Block\LatestPurchasesBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - "maxim_cms.block.latest_purchases"
            - @templating
        calls:
            - [ setPurchaseManager, [@maxim_cms.manager.purchase]]
    maxim_cms.block.purchases:
        public: true
        class: Maxim\CMSBundle\Block\PurchasesBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - "maxim_cms.block.purchases"
            - @templating
        calls:
            - [ setPurchaseManager, [@maxim_cms.manager.purchase]]
            - [ setConfigs, [%maxim_cms.store%]]
    maxim_cms.block.purchases_info:
        public: true
        class: Maxim\CMSBundle\Block\PurchasesInfoBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - "maxim_cms.block.purchases_info"
            - @templating
        calls:
            - [ setPurchaseManager, [@maxim_cms.manager.purchase]]
            - [ setConfigs, [%maxim_cms.store%]]
    maxim_cms.block.recache:
        public: true
        class: Maxim\CMSBundle\Block\RecacheBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - "maxim_cms.block.recache"
            - @templating
# MANAGERS
    maxim_cms.manager.user:
        class: Maxim\CMSBundle\Entity\UserManager
        arguments:
            em: @doctrine.orm.entity_manager
            class: Maxim\CMSBundle\Entity\User
    maxim_cms.manager.purchase:
        class: Maxim\CMSBundle\Entity\PurchaseManager
        arguments:
            em: @doctrine.orm.entity_manager
            class: Maxim\CMSBundle\Entity\Purchase
# TWIG
    maxim_cms.twig.extension.friend:
        class: Maxim\CMSBundle\Twig\Extension\FriendTwigExtension
        arguments: [ @doctrine, @security.context ]
        tags:
            - { name: twig.extension }
    maxim_cms.text.twig.extension:
        class: Maxim\CMSBundle\Twig\Extension\TextExtension
        arguments: [ @doctrine, @security.context ]
        tags:
            - { name: twig.extension }
    maxim_cms.seo.twig.extension:
        class: Maxim\CMSBundle\Twig\Extension\SeoExtension
        tags:
            - { name: twig.extension }
# LISTENERS
    maxim_cms.listener.minecraft_send:
        class: Maxim\CMSBundle\Listeners\MinecraftSendListener
        tags:
            - { name: kernel.event_listener, event: minecraft.send, method: onMinecraftSend }
        arguments: [ @logger, @minecraft.helper, @doctrine.orm.entity_manager]
    maxim_cms.listener.announcement:
        class: Maxim\CMSBundle\Listeners\AnnouncementListener
        tags:
            - { name: kernel.event_listener, event: announcement.create, method: onAnnouncementCreate }
        arguments: [ @logger, @doctrine.orm.entity_manager ]

# REPOSITORIES
    maxim_cms.repository.purchase:
       class: Maxim\CMSBundle\Entity\PurchaseRepository
       arguments: [MaximCMSBundle:Purchase]
       factory_service: doctrine.orm.entity_manager
       factory_method: getRepository
       calls:
           - [ setWebsiteId, [%website%]]